server:
  port: 8070
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-vehiculos
          uri: lb://ms-vehiculos
          predicates:
            - Path=/api/register/**
        - id: ms-lista-reparacines
          uri: lb://ms-lista-reparaciones
          predicates:
            - Path=/api/reparaciones/**
        - id: ms-reparaciones-vehiculos
          uri: lb://ms-reparaciones-vehiculos
          predicates:
            - Path=/api/historial/**
        - id: ms-reportes
          uri: lb://ms-reportes
          predicates:
            - Path=/api/reportes/**
