server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-vehiculos
          uri: lb://ms-vehiculos
          predicates:
            - Path=/api/register/**
        - id: ms-lista-reparacines
          uri: lb://ms-lista-reparaciones
          predicates:
            - Path=/api/reparaciones/**
        - id: ms-reparaciones-vehiculos
          uri: lb://ms-reparaciones-vehiculos
          predicates:
            - Path=/api/historial/**
        - id: ms-reportes
          uri: lb://ms-reportes
          predicates:
            - Path=/api/reportes/**
