apiVersion : apps/v1
kind: Deployment
metadata:
  name: ms-reparaciones-vehiculos-deployment
  labels:
    app: ms-reparaciones-vehiculos-deployment
spec:
  selector:
    matchLabels:
      app: ms-reparaciones-vehiculos-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-reparaciones-vehiculos-deployment
    spec:
      containers:
        - name: ms-repairvehicles
          image: zthfelipe/ms-reparaciones-vehiculos
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REPAIRVEHICLE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REPAIRVEHICLE
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_REPAIRVEHICLE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD

